export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_ALL_CATEGORIES_FAILURE = 'GET_ALL_CATEGORIES_FAILURE';

export const COMMENT_VOTE = 'COMMENT_VOTE';
export const COMMENT_VOTE_FAILURE = 'COMMENT_VOTE_FAILURE';

export const CREATED_COMMENT = 'CREATED_COMMENT';
export const CREATED_COMMENT_FAILURE = 'CREATED_COMMENT_FAILURE';

export const DELETED_COMMENT = 'DELETED_COMMENT';
export const DELETED_COMMENT_FAILURE = 'DELETED_COMMENT_FAILURE';

export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENTS_FAILURE = 'GET_COMMENTS_FAILURE';

export const UPDATED_COMMENT = 'UPDATED_COMMENT';
export const UPDATED_COMMENT_FAILURE = 'UPDATED_COMMENT_FAILURE';


export const CREATED_POST = 'CREATED_POST';
export const CREATED_POST_FAILURE = 'CREATED_POST_FAILURE';

export const DELETED_POST = 'DELETED_POST';
export const DELETED_POST_FAILURE = 'DELETED_POST_FAILURE';

export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const GET_ALL_POSTS_FAILURE = 'GET_ALL_POSTS_FAILURE';

export const POST_VOTE = 'POST_VOTE';
export const POST_VOTE_FAILURE = 'POST_VOTE_FAILURE';

export const UPDATED_POST = 'UPDATED_POST';
export const UPDATED_POST_FAILURE = 'UPDATED_POST_FAILURE';
